modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="pixelmod"
version="0.0.1"
displayName="Pixelmod"
displayURL="No Url"
credits="No Credits"
authors="Tapwatero"
description='''No Description'''

[[dependencies.pixelmod]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.pixelmod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"


[[dependencies.pixelmod]]
modId="pixelmon"
mandatory=true
versionRange="[9.0.6, 9.2.0)"
ordering="NONE"
side="CLIENT"